name: build
on:
  workflow_dispatch:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: python-install
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: build sdist
      run: |
        sudo apt update
        sudo apt install libjerasure-dev -y
        pip install wheel cython
        python setup.py build_ext --inplace sdist
        pip uninstall cython -y
        
    - name: install/test sdist
      run: |
        pip install dist/*.tar.gz
        pip install pytest
        pytest tests
        rm dist/*-linux*.whl

    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
        
