name: build
on:
  workflow_dispatch:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: python-install
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: build sdist
      run: |
        sudo apt update
        sudo apt install libjerasure-dev -y
        pip install wheel cython
        python setup.py build_ext --inplace sdist
        pip uninstall cython -y
        
    - name: install/test sdist
      run: |
        pip install dist/*.tar.gz
        pip install pytest
        pytest tests

    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
        
  manylinux:
    name: manylinux ${{matrix.platform}}-${{matrix.arch}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64] #[x86_64, aarch64]
        platform: [manylinux_2_24] #[manylinux2014, manylinux_2_24]
    container: quay.io/pypa/${{matrix.platform}}_${{matrix.arch}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          scripts/manylinux.sh
      
        
