name: build
on:
  workflow_dispatch:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: python-install
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: install
      run: |
        python setup.py sdist
        pip install dist/*.tar.gz
        pip install pytest
        pytest tests
        
