name: manual-build

env:
  REPO_NAME: jerasure
  REPO: https://github.com/ktnrg45/jerasure.git
  MSVC_VER: "Visual Studio 15 2017"
on:
  workflow_dispatch:

jobs:
  build_windows:
    name: build windows
    runs-on: [self-hosted]
    strategy:
      matrix:
        include:
          - arch: x64
            version: 3.8
#         - platform: windows-2016
#           arch: x64
#         - platform: windows-2016
#           arch: x86
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build-deps-msvc
        run: |
          cd
          git clone --recurse-submodules ${{ env.REPO }}
          cd ${{ env.REPO_NAME }}
          mkdir build
          cd build
          cmake.exe -G "${{ env.MSVC_VER }}" -A ${{ matrix.arch }} ..
          cmake.exe --build . --config Release

#       - name: install-python
#         uses: actions/setup-python@v2
#         with:
#           architecture: ${{ matrix.arch }}
#           python-version: ${{ matrix.version }}

      - name: build-wheel
        run: |
          python -m venv venv
          mkdir venv/libs
          mkdir Include
          cp jerasure/include/*.h venv/Include
          cp jerasure/gf-complete/include/*.h venv/Include
          cp jerasure/build/Release/*.lib venv/libs
          cp jerasure/build/gf-complete/Release/*.lib venv/libs
          venv/scripts/activate
          python -m pip install Cython wheel pytest
          python setup.py bdist_wheel
          # run tests on built wheel
          python -m pip install dist/$(ls dist)
          pytest tests
